#==========================  Modules configuration =============================
filebeat.modules:

  - module: system
    syslog:
    auth:

#========================== Filebeat autodiscover ==============================

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
#=========================== Filebeat inputs ==============================
filebeat.inputs:
  #------------------------------ Docker input --------------------------------
  - type: docker
    enabled: true
    containers.ids:
      - "*"
    paths:
      - /var/lib/docker/containers/${data.docker.container.id}/*.log
    multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
    multiline.match: after
    processors:
      - add_docker_metadata: ~
      - add_cloud_metadata: ~
      - add_locale: ~

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["elastic:9200"]

#============================== Dashboards =====================================
setup.kibana:
  host: "kibana:5601"



